try{
    // console.log("")
    console.log(a[0]);
}
catch(err){
    console.log("Catch run easily",err);
}
finally{
    console.log("--Finally--");
}